### ISSUE TITLE
Using msgctxt

### ISSUE THREAD

**Issue by overbyte** [mikeedwards/po2json#67] opened 2017-10-09 14:57 UTC
We currently have po2json in a system that we're adding msgctxt for each translation string.

the current output from po2json prepends the context to the id: 
```json
'label\u0004Open the QR code on your mobile device.': [ null, '' ],
```

Is this the expected output? As far as I can see, I would have to then split the id on \u0004 and test to see what the length of that was to see if there was a context in the output id but this seems like a bit of a kludge.

**Comment by aleixsuau** [comment] 2018-02-01 09:32
Hi @overbyte,
I had the same issue and fixed it replacing the line 54 of parse.js with this:
````
result[translationKey] = t.msgid_plural ?
                                        [t.msgid_plural].concat(t.msgstr) :
                                        t.msgstr;
````
From what I've seen, seems that the library is designed with the plurals in mind (msgid_plural), when there aren't it is giving a null value as a first value of the translation array.

I don't know if it was by design (@mikeedwards ), but in my project (angular-cli) this was producing a comma ',' preceding each translation.

With this change it's not happening anymore.

**Comment by mikeedwards** [comment] 2018-02-01 13:39
Heya @aleixsuau and @overbyte ! Do you have some sample translation files we could use to build a test around this? It does sound like it could be an issue, but I'd want to make sure a fix doesn't blow up anything else in the test suite or for other translators downstream. Thanks!

**Comment by aleixsuau** [comment] 2018-02-06 09:04
Hi @mikeedwards ,
Thanks for your answer, here you have a sample:
`````
msgid ""
msgstr ""
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Project-Id-Version: \n"
"POT-Creation-Date: \n"
"PO-Revision-Date: \n"
"Language-Team: \n"
"X-Generator: Poedit 1.8.12\n"
"Last-Translator: \n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"Language: de\n"

msgid "No Internet Connection"
msgstr "Sin conexión a internet"

msgid "Internet Connection is Back"
msgstr "La conexión a internet a vuelto"

msgid "New item CREATED at"
msgstr "Nuevo item creado en"

msgid "Item SAVED to"
msgstr "Item SAVED to"

msgid "Item DELETED from"
msgstr "Item eliminado de"

msgid "Not found"
msgstr "No encontrado"

msgid "Error in"
msgstr "Error en"

msgid "This error has been reported to the Administrator with the ID:"
msgstr "El error ha sido reportado al Administrador con la id:"
`````
Let me know if you need something else.

Thanks for your work! :)

**Comment by aleixsuau** [comment] 2018-05-21 14:00
Hi @mikeedwards , 
Did you solve this issue?
Thanks

**Comment by aleixsuau** [comment] 2018-09-24 11:03
Hi @mikeedwards ,
Did you solve this issue?
Thanks

**Comment by mikeedwards** [comment] 2018-09-24 14:57
Ahhh, ok, I think I see what may be the problem. I tried the change at line 52, and it broke half the tests. 

But I also noticed that the expected format appeared to be like what Jed does in versions >= 1.1.0. (This has been messing up a bunch of other people who use current versions of Jed.)

Because of a format change in Jed around 1.1, we had to introduce an option for that specific set of versions (up to and including the current version), but maintain defaults, options, etc for legacy projects so that wouldn't blow up unexpectedly if that hadn't specified a format option, since _old_ Jed is the default.

If you're using Jed 1.1 or greater, you need to do either:
`po2json.parse(your_po_stream, { format: 'jed1.x' })` in code
or
`po2json .\path\to\lang.po .\path\to\lang.json -f jed1.x` from the command line

Old Jed doesn't require the format option.

I'd honestly be in favor of making Jed > 1.1.0 the default for exactly these reasons, but since there are a LOT of projects that use po2json somewhere deep in their builds, I'd want to do that really carefully and with lots of notice, since it'd be a breaking change for those people. If folks have thoughts on the best way to roll that out, I'd be grateful.

All that being said, I'm going to add a couple of extra tests with the PO file @aleixsuau sent since 1) we don't have a Spanish test PO file yet and I'd like to have as many languages represented as possible and 2) it will hopefully demonstrate the difference between the two Jed format options.

Sorry for the confusion. I'll post the test changes along with the generated `json` files—if those seem like they're accurate (particularly the Jed 1.x version), then we can close this ticket.

**Comment by mikeedwards** [comment] 2018-09-24 15:57
Sorry, forgot to mention the delimiter issue. According to the Jed's own tests, using `u0004` is apparently what they want, and matches the gettext spec:

https://github.com/messageformat/Jed/blob/351c47d5c57c5c81e418414c53ca84075c518edb/test/tests.js#L8

also see:
https://github.com/messageformat/Jed/blob/351c47d5c57c5c81e418414c53ca84075c518edb/test/tests.js#L150

Personally, I think that's... odd. But it matches what Jed and gettext seem to want, so we'll stick with it. 

FWIW, messageformat does something different and there's no spec requirement to use that `u0004` delimiter. If people are interested or getting bogged down with Jed, I could add a dep for [gettext-to-messageformat](https://github.com/messageformat/gettext-to-messageformat) which may be helpful (po2json would pretty much just serve as a wrapper for that format.) We have mf formatting now, but it's very primitive.

**Comment by mikeedwards** [comment] 2020-01-09 15:58
The latest mf and jed options make this pretty much obsolete, so I'm going to close. Let me know if there are problems, though, in the latest or 1.0.0 alpha versions.

**Closed by mikeedwards** 2020-01-09 15:58 UTC
